name: Meshery Playground - Reboot Equinix metal servers
on:
    workflow_dispatch:
    schedule:
      - cron:  '0 */20 * * *'  # Run the job every 20 hours at the 0th minute

jobs:
    reboot:
      name: Reboot Metal servers
      if: github.repository == 'meshery/meshery'
      runs-on: ubuntu-latest 
      steps:
          - name: Download and install Equinix Metal CLI
            run: |
             curl -L https://github.com/equinix/metal-cli/releases/latest/download/metal-linux-amd64 -o metal
             chmod +x metal
             sudo mv metal /usr/local/bin/metal
          - name: Reboot both servers
            env:
              METAL_AUTH_TOKEN: ${{ secrets.METAL_AUTH_TOKEN }}
            run: |
             METAL_AUTH_TOKEN=$METAL_AUTH_TOKEN metal device reboot -i ${{ secrets.METAL_SERVER1 }} 
             METAL_AUTH_TOKEN=$METAL_AUTH_TOKEN metal device reboot -i ${{ secrets.METAL_SERVER2 }} 


